<select size="7" name="" id="courses">
	<option value="AEROST">Aerospace Studies</option>
	<option value="AFLANG">African Languages</option>
	<option value="AFRCST">African Studies</option>
	<option value="AFRKAAN">Afrikaans</option>
	<option value="AFROAM">Afro-American Studies</option>
	<option value="AMIND">American Indian Studies</option>
	<option value="ANNEA">Ancient Near East</option>
	<option value="ANES">Anesthesiology</option>
	<option value="ANTHRO">Anthropology</option>
	<option value="APPLING">Applied Linguistics</option>
	<option value="ARABIC">Arabic</option>
	<option value="ARCHEOL">Archaeology</option>
	<option value="ARCHUD">Architecture and Urban Design</option>
	<option value="ARMENIA">Armenian</option>
	<option value="ART">Art</option>
	<option value="ARTHIS">Art History</option>
	<option value="ARTARC">Arts and Architecture</option>
	<option value="ASIAN">Asian</option>
	<option value="ASIAAM">Asian American Studies</option>
	<option value="ASTR">Astronomy</option>
	<option value="AOSCI">Atmospheric and Oceanic Sciences </option>
	<option value="BERBER">Berber</option>
	<option value="BIOENGR">Bioengineering</option>
	<option value="BIOINFO">Bioinformatics</option>
	<option value="BIOLCH">Biological Chemistry</option>
	<option value="BIOMATH">Biomathematics</option>
	<option value="BIOMED">Biomedical Engineering</option>
	<option value="BMEDPHY">Biomedical Physics</option>
	<option value="BMDRES">Biomedical Research</option>
	<option value="BIOSTAT">Biostatistics</option>
	<option value="BULGAR">Bulgarian</option>
	<option value="CEESTD">Central and East European Studies </option>
	<option value="CHENGR">Chemical Engineering</option>
	<option value="CHEM">Chemistry and Biochemistry</option>
	<option value="CHICANO">Chicana and Chicano Studies</option>
	<option value="CHIN">Chinese</option>
	<option value="CIVIC">Civic Engagement</option>
	<option value="CEE">Civil and Environmental Engineering</option>
	<option value="CLASSIC">Classics</option>
	<option value="COMMST">Communication Studies</option>
	<option value="COMHLT">Community Health Sciences</option>
	<option value="COMLIT">Comparative Literature</option>
	<option value="CSBIO">Computational and Systems Biology</option>
	<option value="COMSCI">Computer Science</option>
	<option value="CAEM">Conservation of Archaeological Ethnographi...</option>
	<option value="CZECH">Czech</option>
	<option value="DANCE">Dance</option>
	<option value="DENT">Dentistry</option>
	<option value="DESMA">Design | Media Arts</option>
	<option value="DGTHUM">Digital Humanities</option>
	<option value="DISSTD">Disability Studies</option>
	<option value="DUTCH">Dutch</option>
	<option value="ESSCI">Earth and Space Sciences</option>
	<option value="EASTD">East Asian Studies</option>
	<option value="EEBIOL">Ecology and Evolutionary Biology </option>
	<option value="ECON">Economics</option>
	<option value="EDUC">Education</option>
	<option value="ELENGR">Electrical Engineering</option>
	<option value="ENGR">Engineering</option>
	<option value="ENGL">English</option>
	<option value="ESL">English as a Second Language </option>
	<option value="ENGCOMP">English Composition</option>
	<option value="ENVIRON">Environment</option>
	<option value="ENVHLT">Environmental Health Sciences</option>
	<option value="ENVSCI">Environmental Science and Engineering</option>
	<option value="EPIDEM">Epidemiology</option>
	<option value="ETHNOMU">Ethnomusicology</option>
	<option value="EUROST">European Studies</option>
	<option value="FAMMED">Family Medicine</option>
	<option value="FILIPNO">Filipino</option>
	<option value="FILMTV">Film and Television</option>
	<option value="FRNCH">French</option>
	<option value="GECLST">General Education Clusters</option>
	<option value="GEOG">Geography</option>
	<option value="GERMAN">German</option>
	<option value="GRNTLGY">Gerontology</option>
	<option value="GLBLST">Global Studies</option>
	<option value="GREEK">Greek</option>
	<option value="HLTSER">Health Services</option>
	<option value="HEBREW">Hebrew</option>
	<option value="HINURD">Hindi-Urdu</option>
	<option value="HIST">History</option>
	<option value="HNRS">Honors Collegium</option>
	<option value="HUMCS">Human Complex Systems</option>
	<option value="HUMGEN">Human Genetics</option>
	<option value="HUNGRN">Hungarian</option>
	<option value="ILA">Indigenous Languages of the Americas</option>
	<option value="IESTD">Indo-European Studies</option>
	<option value="INDO">Indonesian</option>
	<option value="INFSTD">Information Studies</option>
	<option value="INTLDV">International Development Studies</option>
	<option value="IRANIAN">Iranian</option>
	<option value="ISLAMIC">Islamics</option>
	<option value="ISLMST">Islamic Studies</option>
	<option value="ITALIAN">Italian</option>
	<option value="JAPAN">Japanese</option>
	<option value="JEWISH">Jewish Studies</option>
	<option value="KOREA">Korean</option>
	<option value="LBRWS">Labor and Workplace Studies</option>
	<option value="LATIN">Latin</option>
	<option value="LATNAM">Latin American Studies</option>
	<option value="LAW">Law</option>
	<option value="UGLAW">Law, Undergraduate</option>
	<option value="LGBTS">Lesbian, Gay, Bisexual, and Transgender St...</option>
	<option value="LIFESCI">Life Sciences</option>
	<option value="LING">Linguistics</option>
	<option value="LITHUAN">Lithuanian</option>
	<option value="MGMT">Management</option>
	<option value="MATSCI">Materials Science and Engineering</option>
	<option value="MATH">Mathematics</option>
	<option value="MECHAE">Mechanical and Aerospace Engineering</option>
	<option value="MEDHIS">Medical History</option>
	<option value="MED">Medicine</option>
	<option value="MIMG">Microbiology, Immunology, and Molecular Ge...</option>
	<option value="MENAS">Middle Eastern and North African Studies</option>
	<option value="MILSCI">Military Science</option>
	<option value="MPHARM">Molecular and Medical Pharmacology</option>
	<option value="MOLBIO">Molecular Biology</option>
	<option value="MCDBIO">Molecular, Cell, and Developmental Biology</option>
	<option value="MCIP">Molecular, Cellular, and Integrative Physi...</option>
	<option value="MOLTOX">Molecular Toxicology</option>
	<option value="MIASTD">Moving Image Archive Studies</option>
	<option value="MUSIC">Music</option>
	<option value="MUSHST">Music History</option>
	<option value="MUSIND">Music Industry</option>
	<option value="MUSCLGY">Musicology</option>
	<option value="NAVSCI">Naval Science</option>
	<option value="NREAST">Near Eastern Languages</option>
	<option value="NEURBIO">Neurobiology</option>
	<option value="NEURLGY">Neurology</option>
	<option value="NEUROSC">Neuroscience</option>
	<option value="NEURO">Neuroscience (Graduate)</option>
	<option value="NEURSGY">Neurosurgery</option>
	<option value="NURSING">Nursing</option>
	<option value="OBGYN">Obstetrics and Gynecology</option>
	<option value="OPTH">Opthalmology</option>
	<option value="ORLBIO">Oral Biology</option>
	<option value="ORTHPDC">Orthopaedic Surgery</option>
	<option value="PATH">Pathology and Laboratory Medicine</option>
	<option value="PEDS">Pediatrics</option>
	<option value="PHILOS">Philosophy</option>
	<option value="PHYSICS">Physics</option>
	<option value="PHYSCI">Physiological Science</option>
	<option value="PHYSIOL">Physiology</option>
	<option value="POLISH">Polish</option>
	<option value="POLSCI">Political Science</option>
	<option value="PORTGSE">Portuguese</option>
	<option value="COMPTNG">Program in Computing</option>
	<option value="PSYCTRY">Psychiatry and Biobehavioral Sciences</option>
	<option value="PSYCH">Psychology</option>
	<option value="PUBHLT">Public Health</option>
	<option value="PUBPLC">Public Policy</option>
	<option value="RADONC">Radiation Oncology</option>
	<option value="RELIGN">Religion, Study of</option>
	<option value="ROMAN">Romanian</option>
	<option value="RUSSIAN">Russian</option>
	<option value="SCAND">Scandinavian</option>
	<option value="SEMITIC">Semitics</option>
	<option value="SERCRO">Serbian/Croatian</option>
	<option value="SLAVIC">Slavic</option>
	<option value="SOCTHT">Social Thought</option>
	<option value="SOCWLF">Social Welfare</option>
	<option value="SOCGEN">Society and Genetics</option>
	<option value="SOCIOL">Sociology</option>
	<option value="SASIAN">South Asian</option>
	<option value="SEASIAN">Southeast Asian</option>
	<option value="SEAST">Southeast Asian Studies</option>
	<option value="SPAN">Spanish</option>
	<option value="STATS">Statistics</option>
	<option value="SURGERY">Surgery</option>
	<option value="THAI">Thai</option>
	<option value="THEATER">Theater</option>
	<option value="TURKIC">Turkic Languages</option>
	<option value="UKRAIN">Ukrainian</option>
	<option value="URBN PL">Urban Planning</option>
	<option value="UROLOGY">Urology</option>
	<option value="VIETMSE">Vietnamese</option>
	<option value="WOMSTD">Women's Studies</option>
	<option value="WLARTS">World Arts and Cultures</option>
	<option value="WLDART">World Arts and Cultures  (Pre-Fall 2011)</option>
	<option value="YIDDSH">Yiddish</option>

</select>